title: "A W "
description: "Quantitative Finance, Machine Learning, Derivatives Pricing, Portfolio Optimization, Risk Analysis"
remote_theme: just-the-docs/just-the-docs

# Just the Docs settings
color_scheme: light # or "light"

search_enabled: true
search:
  rel_url: true
  button: true

markdown: kramdown
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

url: "https://xxxxyyyy80008.github.io"
baseurl: "" 

# Social Links
github_username: xxxxyyyy80008